ALTER TABLE task_config
    ADD COLUMN task_type VARCHAR(20) NOT NULL DEFAULT 'SQL'
        COMMENT '任务类型：SQL / CRAWL';

CREATE TABLE IF NOT EXISTS task_web_crawl_config (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    crawl_name VARCHAR(255) NOT NULL COMMENT '爬取名称',
    crawl_code VARCHAR(255) NOT NULL COMMENT '爬取编码',
    request_url TEXT NOT NULL COMMENT '请求 URL，支持 ${变量}',
    request_method VARCHAR(10) DEFAULT 'GET' COMMENT 'GET / POST / PUT',
    request_headers TEXT COMMENT '请求头 JSON',
    request_params TEXT COMMENT 'URL 参数 JSON',
    request_body TEXT COMMENT 'POST body',
    request_content_type VARCHAR(100) COMMENT 'Content-Type',
    cookies TEXT COMMENT 'Cookie JSON，敏感字段加密存储',
    auth_type VARCHAR(30) DEFAULT 'NONE' COMMENT 'NONE / BASIC / FORM / TOKEN / OAUTH2',
    auth_config TEXT COMMENT '认证配置 JSON，敏感字段加密存储',
    ssh_enabled TINYINT DEFAULT 0 COMMENT '是否启用 SSH 隧道',
    ssh_host VARCHAR(255) COMMENT 'SSH 主机',
    ssh_port INT DEFAULT 22 COMMENT 'SSH 端口',
    ssh_username VARCHAR(255) COMMENT 'SSH 用户名',
    ssh_password VARCHAR(500) COMMENT 'SSH 密码，加密',
    ssh_private_key TEXT COMMENT 'SSH 私钥，加密',
    ssh_passphrase VARCHAR(500) COMMENT '私钥口令，加密',
    ssh_remote_host VARCHAR(255) COMMENT 'SSH 隧道远程目标主机',
    ssh_remote_port INT COMMENT 'SSH 隧道远程目标端口',
    ssh_local_port INT COMMENT '本地端口，0 表示自动分配',
    render_type VARCHAR(20) DEFAULT 'STATIC' COMMENT '渲染模式：STATIC / DYNAMIC',
    driver_config TEXT COMMENT 'WebDriver 配置 JSON',
    output_format VARCHAR(30) DEFAULT 'CSV' COMMENT 'CSV / EXCEL / WORD / PPT / TXT / INLINE',
    template_id BIGINT COMMENT '关联报表模板 ID',
    template_code VARCHAR(255) COMMENT '报表模板编码',
    file_suffix VARCHAR(50) COMMENT '文件后缀',
    file_name_pattern VARCHAR(500) COMMENT '文件名模式',
    description VARCHAR(500) COMMENT '描述',
    custom_params TEXT COMMENT '自定义参数 JSON，替换 URL/Body 中的 ${xxx}',
    status TINYINT DEFAULT 1 COMMENT '状态：1 启用，0 禁用',
    pagination_enabled TINYINT DEFAULT 0 COMMENT '是否启用分页',
    pagination_type VARCHAR(30) COMMENT 'SELECTOR / URL_TEMPLATE',
    pagination_selector VARCHAR(500) COMMENT '下一页 CSS 选择器',
    pagination_url_template VARCHAR(500) COMMENT '分页 URL 模板，如 /list?page=${page}',
    pagination_max_pages INT DEFAULT 1 COMMENT '最大爬取页数',
    media_enabled TINYINT DEFAULT 0 COMMENT '是否下载媒体元素',
    media_selector VARCHAR(500) COMMENT '媒体元素 CSS 选择器，为空默认 img,video,audio,source',
    media_file_types VARCHAR(100) COMMENT 'image / video / audio / all',
    media_storage_config_id BIGINT COMMENT '媒体单独上传的存储配置 ID',
    media_output_mode VARCHAR(30) DEFAULT 'ATTACH' COMMENT 'ATTACH / ZIP / STORE_ONLY / ATTACH_ZIP',
    media_zip_name_pattern VARCHAR(500) COMMENT '打包 ZIP 文件名模式',
    media_filter_config TEXT COMMENT '媒体筛选 JSON',
    chart_enabled TINYINT DEFAULT 0,
    chart_type VARCHAR(20),
    chart_title VARCHAR(255),
    chart_auto_merge TINYINT DEFAULT 1,
    chart_label_rotation VARCHAR(20) DEFAULT 'AUTO',
    chart_background_color VARCHAR(50),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_crawl_code (crawl_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='网页爬取配置';

CREATE TABLE IF NOT EXISTS task_web_crawl_selector (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    crawl_config_id BIGINT NOT NULL COMMENT '关联 crawl_config id',
    crawl_code VARCHAR(255) NOT NULL COMMENT '冗余 crawl_code',
    is_row_selector TINYINT DEFAULT 0 COMMENT '是否为行级选择器，1 表示该选择器用于定位数据行',
    field_name VARCHAR(100) COMMENT '输出字段名；行级选择器可空',
    selector_type VARCHAR(20) NOT NULL COMMENT 'CSS / XPATH / REGEX',
    selector_value TEXT NOT NULL COMMENT '选择器表达式',
    attribute VARCHAR(100) COMMENT 'CSS 属性：text / html / src / attr:xxx',
    data_type VARCHAR(20) DEFAULT 'STRING' COMMENT 'STRING / NUMBER / DATE / LINK / HTML',
    default_value VARCHAR(500) COMMENT '未命中默认值',
    sort_order INT DEFAULT 0 COMMENT '排序',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_crawl_config_id (crawl_config_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='网页爬取字段提取规则';

CREATE TABLE IF NOT EXISTS task_web_crawl_relation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_id BIGINT NOT NULL,
    task_code VARCHAR(255) NOT NULL,
    crawl_id BIGINT,
    crawl_code VARCHAR(255) NOT NULL,
    sort_order INT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_task_code (task_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务与网页爬取配置关系';
